### ISSUE TITLE
Ruby: autocorrect by rubocop does not work when this extension is not the default formatter

### ISSUE THREAD

**Issue by jvilk-stripe** [LoranKloeze/vscode-ruby-rubocop-revived#1]
See https://github.com/misogi/vscode-ruby-rubocop/pull/172 for more details and a fix.

**Comment by LoranKloeze** [comment]
Thanks! I have merged the fix with this repo and published version 0.9.1 to the marketplace. https://marketplace.visualstudio.com/items?itemName=LoranKloeze.ruby-rubocop-revived
