### ISSUE TITLE
[feature request] Allow to hide "Disable/Ignore" suggestions

### ISSUE THREAD

**Issue by marianosimone** [LoranKloeze/vscode-ruby-rubocop-revived#18]
We are planning on using this extension at Stripe, but want to discourage users from using the "Disable"/"Ignore" suggestions, instead of them being easily accessible through quick fixes.

It would be great to have a setting to hide those suggestions.

**Comment by LoranKloeze** [comment]
Thx, will check and release it!

**Comment by marianosimone** [comment]
Any updates?
