### ISSUE TITLE
Autocorrect on 0.9.1 gives unhelpful error

### ISSUE THREAD

**Issue by wujibear** [LoranKloeze/vscode-ruby-rubocop-revived#4]
Unsure if this is just a misconfig on my part, but when trying to run `Ruby: Autocorrect by Rubocop` I get `An error occurred during auto-correction` with no details other than `Source: ruby-rubocop-revived (Extension)`.

My current settings json has this in it:
```
{
    "ruby.rubocop.useBundler": true,
    "editor.defaultFormatter": "LoranKloeze.ruby-rubocop-revived",
    "editor.formatOnSave": true,
    "ruby.format": "rubocop"
}
```

I am on rbenv if that's an issue, but it does seem to show me the correct error squiglies otherwise.
Is there something I'm missing in my setup, or is this a possible bug /unsupported currently?

**Comment by LoranKloeze** [comment]
This extension should run fine with rbenv. Can you open the developer tools (cmd `Developer: Toggle Developer Tools`) and run the command again? Maybe the console log in the developer tools provides some insight.

**Comment by jochambo** [comment]
Running into the same issue here. Same settings as OP. Developer console shows:
```
localProcessExtensionHost.ts:298 Extension Host
localProcessExtensionHost.ts:299 invalid option: --autocorrect Did you mean?  auto-correct For usage information, use --help
```
Running the command from terminal with the `-a` flag works as advertised.

**Comment by jvilk-stripe** [comment]
From changelog:

```
Replace deprecated Rubocop argument --auto-correct with --autocorrect
```

Sounds like they were too quick to change this.

**Comment by jochambo** [comment]
Okay, looks like rubocop changed in [1.30.0](https://github.com/rubocop/rubocop/releases?page=2). Upgrading rubocop fixed ~autocorrect~...auto-correct.

**Comment by LoranKloeze** [comment]
Yes, upgrade to Rubocop >= 1.30.0 will fix this. I'll update the docs. Thx!
