### ISSUE TITLE
Create a configuration option to change the command to execute 

### ISSUE THREAD

**Issue by vittorius** [LoranKloeze/vscode-ruby-rubocop-revived#6]
Hey. 

First of all, thanks for reviving this extension.

My idea is to have something like `ruby.rubocop.command` to be able to change to e.g. `rubocop --server` to utilize the Rubocop [server mode](https://docs.rubocop.org/rubocop/usage/server.html) and thus speedup things a bit 😄

**Comment by LoranKloeze** [comment]
Thx for the compliment!

The `--server` option is already implemented but it's poorly documented as it's only mentioned in [CHANGELOG.md](https://github.com/LoranKloeze/vscode-ruby-rubocop-revived/blob/master/CHANGELOG.md) at 0.9.0. 

I will update the README.
