### ISSUE TITLE
`useServer` option not respected for non-autocorrect runs

### ISSUE THREAD

**Issue by jvilk-stripe** [LoranKloeze/vscode-ruby-rubocop-revived#8]
`rubocop.ts` calls `getCommandArguments` but doesn't append `--server` to the CLI args. In contrast, `rubocopAutocorrectProvider.ts` does append `--server`.

Maybe `getCommandArguments` should accept `useServer` as a parameter so this mistake is easy to avoid?

**Comment by jvilk-stripe** [comment]
If I force the `--server` option, I get the following error:

```
Error on parsing output (It might non-JSON output) : "RuboCop server starting on 127.0.0.1:35383. {"metadata":{"rubocop_version":"1.31.2","ruby_engine":"ruby","ruby_version":"2.7.2","ruby_patchlevel":"137","ruby_platform":"x86_64-linux"},"files":[{"path":"scripts/bin/rubocop-server/rubocop.rb","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}"
```

There's no way to prevent RuboCop from spewing this line. You'll need to manually strip it from the output before JSON parsing.

**Comment by LoranKloeze** [comment]
Thanks for raising the issue. Would you like to create a PR for this?
